### ISSUE TITLE
[PE-D] tedit in application example does not work 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#201]
Copy pasting the in application example shown when just typing `tedit`, which is `tedit /t 1/n group meeting /d 24/10/2021 23:59` does not work 

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: sivayogasubramanian/ped#13

**Comment by leeroy999** [comment]
Fixed in #233
