### ISSUE TITLE
[PE-D] Deleting a member who is attending an event is allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#207]
There should be some kind of restriction regards to this aspect. This causes problems with other commands.

For example: How do i mark attendance for a member who is deleted but is attending an event? I can use the `emarkall` command but thats about it. I am unable to do anything specific to the person deleted.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: sivayogasubramanian/ped#16

**Comment by leeroy999** [comment]
Thank you for the suggestion, but we will not be adding features in v1.4.
