### ISSUE TITLE
[PE-D] Adding a task command documentation error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#215]
Adding a task command documentation in userguide does not contain compulsory input `/d TASKDEADLINE` 
resulting in the following examples in the user guide not working as intended :

`tadd /n Collect payment from members /m 3`

`tadd /n Collect dogtag /m 1 /m 2 /m 3`

![Screenshot 2021-10-29 at 4.50.50 PM.png](https://raw.githubusercontent.com/nzixuan/ped/main/files/fa0ce8a4-407a-48ae-ac13-a9f9d5484b85.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: nzixuan/ped#3

**Comment by leeroy999** [comment]
Fix in #233
