### ISSUE TITLE
[PE-D] tadd differs from what is expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#219]
In UG, tadd doesn't have the deadline parameter and is probably expected not to as its a todo. But the app requires the users to enter deadlines. 

![image.png](https://raw.githubusercontent.com/Shruthi0310/ped/main/files/8fae489a-e950-490e-8f79-2d2b011ff47b.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Shruthi0310/ped#8

**Comment by leeroy999** [comment]
Fix in #233
