### ISSUE TITLE
[PE-D] eadd incomplete UG description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#223]
![image.png](https://raw.githubusercontent.com/darrenhoon/ped/main/files/0dac6231-f30b-45a5-b6e0-b8c4365c622e.png)

The UG mentioned that if a specified user is already in the event, an error is thrown. However, in this case, the 9th index user has not been added yet, only the 8th, yet the error is thrown as shown below:

![image.png](https://raw.githubusercontent.com/darrenhoon/ped/main/files/0673dfc3-6c41-4a6a-a293-5c6fc8c0a102.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: darrenhoon/ped#13

**Comment by leeroy999** [comment]
To change in UG: If any of the specified members are already participating in the event, an error is thrown to the user.
