### ISSUE TITLE
[PE-D] Adding multiple member and events

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#224]
Redundant member adding require multiple instances of writing `/m` 
for example adding members to events require the command `emadd /e 1 /m 2 /m 3  /m 4  /m 5` 
when multiple members are added to an event it becomes increasingly repetitive.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: nzixuan/ped#5

**Comment by leeroy999** [comment]
Suggestion noted, but we are not adding new features in v1.4.
