### ISSUE TITLE
[PE-D] emark: Not working as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#226]
The emark feature doesn't seem to be working. It shows an error message that the member is not in the event even though he is. But this problem only occurs for marking the first event in the list, it works correctly for other events in the list.

![image.png](https://raw.githubusercontent.com/Shruthi0310/ped/main/files/c71f010e-abb8-454e-b344-a8eb28a92830.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Shruthi0310/ped#10

**Comment by leeroy999** [comment]
fixed in #233
