### ISSUE TITLE
[PE-D] Editing an event name with all members have attended status removes the status after edit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#234]
![image.png](https://raw.githubusercontent.com/sivayogasubramanian/ped/main/files/37e09c17-9952-45b8-8598-fd24af4973cf.png)

Command used: `eedit /e 1 /n change name`

![image.png](https://raw.githubusercontent.com/sivayogasubramanian/ped/main/files/66be2b30-1111-4eec-82bf-f218eb014e61.png)

The status is removed?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: sivayogasubramanian/ped#18

**Comment by Samuel-bit-prog** [comment]
Closed. Fixed with pr
