### ISSUE TITLE
[PE-D] Command decription in the application is wrong

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T15-2/tp#235]
![image.png](https://raw.githubusercontent.com/sivayogasubramanian/ped/main/files/773a707c-375d-43cc-a8f2-117985b0af1a.png)

it should be `displayed members list`

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: sivayogasubramanian/ped#19

**Comment by leeroy999** [comment]
To change to:
Add members to the event identified by the corresponding indexes
