### ISSUE TITLE
A help/tutorial/guide.

### ISSUE THREAD

**Issue by GWphua** [AY2122S1-CS2103T-T15-2/tp#30]
As a user, I want to know how to use the application, so that I can troubleshoot any problems myself easily.

**Comment by leeroy999** [comment]
Implemented in [UserGuide](https://ay2122s1-cs2103t-t15-2.github.io/tp/UserGuide.html) and [DeveloperGuide](https://ay2122s1-cs2103t-t15-2.github.io/tp/DeveloperGuide.html)
